"""
Flixbus Pricing Agent
---------------------
Reads the flagging output Excel, extracts CRITICAL flags,
and uses Gemini to generate a plain-English daily pricing brief
that a pricing analyst would otherwise have to write manually.
"""

import pandas as pd
from google import genai
from datetime import datetime

# ── CONFIG ────────────────────────────────────────────────────────────────────
API_KEY    = ""
INPUT_FILE  = ""
OUTPUT_FILE = ""
# ─────────────────────────────────────────────────────────────────────────────

client = genai.Client(api_key=API_KEY)


def load_critical_flags(filepath: str) -> pd.DataFrame:
    df = pd.read_excel(filepath, sheet_name="Flagging Output")

    # Date already parsed as datetime by openpyxl
    if pd.api.types.is_datetime64_any_dtype(df["Departure Date"]):
        df["Departure Date"] = df["Departure Date"].dt.strftime("%d %b %Y")
    else:
        df["Departure Date"] = pd.to_datetime(
            df["Departure Date"], origin="1899-12-30", unit="D"
        ).dt.strftime("%d %b %Y")

    critical = df[df["Flag Severity"] == "CRITICAL"].copy()

    # Sort by absolute deviation (worst first) and take top 20
    critical["Abs Diff %"] = critical["WAP Diff % vs Median"].abs()
    critical = critical.sort_values("Abs Diff %", ascending=False).head(20)
    return critical


def format_flags_for_prompt(df: pd.DataFrame) -> str:
    lines = []
    for _, row in df.iterrows():
        direction = row.get("Flag Direction", "")
        load = row["Load Factor"]
        load_str = f"{float(load):.0%}" if pd.notna(load) else "N/A"
        lines.append(
            f"- Route: {row['Route Number']} | Date: {row['Departure Date']} | "
            f"Dep: {row['Flixbus Departure Time']} | Product: {row['Flixbus Product']} | "
            f"Flixbus WAP: ₹{row['Flixbus WAP']:.0f} | Peer Median: ₹{row['Peer Median WAP']:.0f} | "
            f"Diff: {row['WAP Diff % vs Median']:.1f}% | Direction: {direction} | "
            f"Load Factor: {load_str} | Top 20% Rank: {row['Is Top 20% Rank']} | "
            f"Confidence: {row['Confidence']}"
        )
    return "\n".join(lines)


def generate_brief(flags_text: str, total_critical: int) -> str:
    today = datetime.today().strftime("%d %b %Y")

    prompt = f"""
You are a pricing analyst at Flixbus India. You have just run the daily pricing pipeline.

Today is {today}. There are {total_critical} CRITICAL pricing flags that require immediate attention.

Here are the CRITICAL flags:
{flags_text}

Write a concise daily pricing brief for the pricing team. For each flag:
- State the route, date, and departure time
- Explain what is wrong in plain English (overpriced or underpriced, by how much)
- Give a specific, actionable recommendation (e.g. "Increase WAP by ₹X–Y", "Reduce WAP by ₹X")
- Note any context that justifies or explains the flag (load factor, rank, confidence)

Format it as a professional daily brief. Be direct and action-oriented.
Start with a 2-line executive summary of the overall situation, then go flag by flag.
End with a priority order — which flags to act on first and why.
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text


def main():
    print("=" * 60)
    print("  FLIXBUS DAILY PRICING AGENT")
    print("=" * 60)

    print("\n[1/3] Loading flagging output...")
    critical_df = load_critical_flags(INPUT_FILE)
    print(f"      Found {len(critical_df)} CRITICAL flags")

    if critical_df.empty:
        print("      No CRITICAL flags today. All prices within acceptable range.")
        return

    print("\n[2/3] Sending to Gemini for analysis...")
    flags_text = format_flags_for_prompt(critical_df)
    brief = generate_brief(flags_text, len(critical_df))

    print("\n[3/3] Writing brief to output file...")
    today = datetime.today().strftime("%d %b %Y")
    header = f"FLIXBUS DAILY PRICING BRIEF — {today}\nGenerated by AI Pricing Agent\n{'='*60}\n\n"

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(header + brief)

    print(f"      Saved to: {OUTPUT_FILE}")

    print("\n" + "=" * 60)
    print("  BRIEF PREVIEW")
    print("=" * 60)
    print(brief[:1500])
    if len(brief) > 1500:
        print(f"\n... [{len(brief)-1500} more characters in full output file]")


if __name__ == "__main__":
    main()